config_dict:
  activation: relu
  kernel_initializer: glorot_uniform
  learner_replay_port: '5554'
  replay_addr: 127.0.0.1
  storage_hostname: 127.0.0.1
  storage_password: EA00E05EC7592F8A4B41FED9B30A3D26
  storage_port: '5553'
  storage_username: ehuang
game: !!python/object:game_configs.cartpole_config.CartPoleConfig
  has_legal_moves: false
  is_deterministic: true
  is_discrete: true
  is_image: false
  max_score: 500
  min_score: 0
