config_dict:
  adam_epsilon: 0.00375
  advatage_hidden_layers_widths:
  - 64
  - 64
  atom_size: 81
  clipnorm: 2.0
  dense_layer_widths:
  - 128
  - 128
  discount_factor: 0.99
  kernel_initializer: glorot_uniform
  learning_rate: 0.005
  loss_function: !!python/object:utils.utils.KLDivergenceLoss
    axis: -1
    from_logits: false
  min_replay_buffer_size: 1250
  minibatch_size: 128
  n_step: 9
  per_alpha: 0.8
  per_beta: 0.45
  per_epsilon: 0.05
  replay_buffer_size: 10000
  replay_interval: 4
  training_steps: 10000
  transfer_interval: 10
  value_hidden_layers_widths:
  - 64
  - 64
game: !!python/object:game_configs.cartpole_config.CartPoleConfig
  has_legal_moves: false
  is_deterministic: true
  is_discrete: true
  is_image: false
  max_score: 500
  min_score: 0
  multi_agent: false
  num_players: 1
  perfect_information: true
