config_dict:
  rank: 3
  worker_name: 'actor'
  world_size: 4
  pg_port: 3334
  rpc_port: 3333
  master_addr: 127.0.0.1
  replay_addr: 127.0.0.1
  storage_addr: 127.0.0.1
  loss_function: !!python/object:utils.utils.CategoricalCrossentropyLoss
    axis: -1
    from_logits: false
game: !!python/object:game_configs.cartpole_config.CartPoleConfig
  has_legal_moves: false
  is_deterministic: true
  is_discrete: true
  is_image: false
  max_score: 500
  min_score: 0
