config_dict:
  rank: 0
  worker_name: 'learner'
  world_size: 4
  rpc_port: 3333
  replay_addr: 127.0.0.1
  storage_addr: 127.0.0.1
  distributed_actor_config_file: './configs/actor_config_example.yaml'
  loss_function: !!python/object:utils.utils.CategoricalCrossentropy
    axis: -1
    from_logits: false
  num_actors: 1
game: !!python/object:game_configs.cartpole_config.CartPoleConfig
  has_legal_moves: false
  is_deterministic: true
  is_discrete: true
  is_image: false
  max_score: 500
  min_score: 0
