config_dict:
  adam_epsilon: 1.0e-08
  advantage_hidden_layer_widths:
  - 128
  - 128
  clipnorm: 0.0
  dense_layer_widths:
  - 128
  - 256
  - 256
  - 128
  discount_factor: 0.99
  eg_epsilon: 1
  eg_epsilon_decay_type: linear
  eg_epsilon_final: 0.0
  eg_epsilon_final_step: 5000
  learning_rate: 0.002
  loss_function: !!python/object:utils.utils.KLDivergenceLoss
    axis: -1
    from_logits: false
  min_replay_buffer_size: 256
  minibatch_size: 256
  num_minibatches: 4
  per_alpha: 0
  per_beta: 0
  per_beta_final: 0.5
  per_epsilon: 0.001
  replay_buffer_size: 1000000
  replay_interval: 64
  training_steps: 20000
  transfer_interval: 1024
  value_hidden_layer_widths:
  - 128
  - 128
game: !!python/object:cfr_utils.EmptyConf
  has_legal_moves: true
  is_discrete: true
  max_score: 1200
  min_score: -1200
  num_players: 1
