config_dict:
  rank: 0
  atoms: 1
  worker_name: 'learner'
  world_size: 6 
  rpc_port: 3333
  master_addr: 127.0.0.1
  replay_addr: 127.0.0.1
  storage_addr: 127.0.0.1
  replay_buffer_size: 100000
  distributed_actor_config_file: './configs/actor_config_example.yaml'
  loss_function: !!python/object:utils.utils.CategoricalCrossentropyLoss
    axis: -1
    from_logits: false
  num_actors: 3
  adam_epsilon: 1.0e-08
  advatage_hidden_layers_widths:
  - 128
  clipnorm: 10.0
  dense_layers_widths:
  - 128
  kernel_initializer: orthogonal
  learning_rate: 0.001
  minibatch_size: 128
  n_step: 3
  per_alpha: 0.2
  per_beta: 0.6
  per_epsilon: 1.0e-06
  replay_interval: 1
  training_steps: 10000
  transfer_interval: 100
  value_hidden_layers_widths:
  - 128
game: !!python/object:game_configs.cartpole_config.CartPoleConfig
  has_legal_moves: false
  is_deterministic: true
  is_discrete: true
  is_image: false
  max_score: 500
  min_score: 0
