config_dict:
  activation: relu
  adam_epsilon: 0.0003125
  advantage_hidden_layers: 0
  atom_size: 51
  clipnorm: null
  conv_layers: !!python/tuple []
  conv_layers_noisy: false
  dense_layers: 2
  dense_layers_noisy: true
  discount_factor: 0.99
  dueling: true
  ema_beta: 0.95
  kernel_initializer: orthogonal
  learning_rate: 0.01
  loss_function: !!python/object:keras.src.losses.CategoricalCrossentropy
    _allow_sum_over_batch_size: false
    _fn_kwargs:
      axis: -1
      from_logits: false
      label_smoothing: 0.0
    _name_scope: categorical_crossentropy
    fn: !!python/name:keras.src.losses.categorical_crossentropy ''
    name: categorical_crossentropy
    reduction: auto
  min_replay_buffer_size: 500
  minibatch_size: 128
  n_step: 3
  noisy_sigma: 0.5
  num_minibatches: 1
  optimizer: !!python/name:keras.src.optimizers.legacy.adam.Adam ''
  per_alpha: 0.5
  per_beta: 0.4
  per_epsilon: 0.001
  replay_buffer_size: 50000
  replay_interval: 2
  soft_update: false
  training_iterations: 1
  training_steps: 30000
  transfer_interval: 100
  value_hidden_layers: 0
  width: 512
game: !!python/object:game_configs.cartpole_config.CartPoleConfig
  has_legal_moves: false
  is_deterministic: true
  is_discrete: true
  is_image: false
  max_score: 500
  min_score: 0
  multi_agent: false
  perfect_information: true
